name: oOf dynamic again

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  SYSTEM_URL: http://tdrive.manofuranium.workers.dev/oppppp7tproosystem.zip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install -y brotli
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar
            sudo -E apt-get install expect
            sudo apt update 2>/dev/null | grep packages

       - name: System.img
         run: |
              sudo aria2c https://tdrive.manofuranium.workers.dev/systemnew/system.img
        
       - name: System.img
         run: |
              sudo mkdir lel
              sudo mount -ro loop system.img lel/
              sudo zip -r op7prosystem.zip lel
              
       - name: Uploading 
         run: |
              expect -c "
              spawn sftp ruiii@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"cd /home/pfs/project/rui-ports/dumps\r\"
              set timeout -1
              send \"put op7prosystem.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
              
       - name: upload aonly n infog
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit op7tprooneplus.zip
 
